services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    ports:
      - ${APP_PORT}:8080
    environment:
      PORT: ${APP_PORT}
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}-db
    image: postgres:${POSTGRES_VERSION}-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
